name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo " Job triggered by event ${{ github.event_name }} on branch ${{ github.ref }}.""

      - uses: actions/checkout@v3.3.0

      - name: List files in repo.
        run: |
          echo "The repo ${{ github.repository }} contains the following files:"
          tree
